Fix _action_to_direction usage
Farama-Foundation/gymnasium-env-template pull request #4
Opened 2024-01-01 22:02 UTC by SarvagyaVaish

# Description

To use the _action_to_direction dict, we need to first convert the numerical action (0, 1, 2, 3) to an Enum.

Fixes https://github.com/Farama-Foundation/gymnasium-env-template/issues/3

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-01-02 19:49 UTC, pseudo-rnd-thoughts requested changes
Could we change the implementation on line 41 instead for it to be `Actions.UP.value` as I think this is still clear what is happening but means we don't need to do this conversion step.

2024-01-02 19:49 UTC, pseudo-rnd-thoughts commented
I just realised that I have already made this change over in Gymnasium but not here
https://gymnasium.farama.org/main/tutorials/gymnasium_basics/environment_creation/#sphx-glr-tutorials-gymnasium-basics-environment-creation-py

2024-01-03 02:06 UTC, SarvagyaVaish commented
> Could we change the implementation on line 41 instead for it to be `Actions.UP.value` as I think this is still clear what is happening but means we don't need to do this conversion step.

Yeah! That's better :)

2024-01-03 10:24 UTC, pseudo-rnd-thoughts approved these changes

2024-01-03 10:33 UTC, merged

2024-01-04 06:09 UTC, SarvagyaVaish commented
@pseudo-rnd-thoughts Tests seem to be [failing](https://github.com/Farama-Foundation/gymnasium-env-template/actions).

However, it's failing on the installation step. Not sure if it's the changes I introduced in this PR. Thoughts?

2024-01-04 10:59 UTC, pseudo-rnd-thoughts commented
@kir0ul is looking into it so I wouldn't worry about it for now. I don't believe that your PR caused the issue

2024-01-04 15:15 UTC, kir0ul commented
The issue was caused by some changes introduced by the Hatchling build backend (https://github.com/pypa/hatch/pull/1089), hopefully PR https://github.com/Farama-Foundation/gymnasium-env-template/pull/5 should fix it.